server.port=8080
server.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/techmovil_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.admin.username=admin
app.admin.password=admin123
app.jwt.signing=fintechmovil-sistema-inventario-2026-ok!
app.cors.origins=http://localhost:5173,https://fintechmovil.vercel.app

logging.level.com.example.techmovil=INFO
