sonar.projectKey=fintechmovil-frontend
sonar.projectName=FinTechMovil Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.coverage.exclusions=src/**

sonar.javascript.node.maxspace=4096

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S1082
sonar.issue.ignore.multicriteria.e1.resourceKey=src/App.jsx
