services:
  db:
    image: mysql:8.0
    container_name: techmovil_db
    restart: always
    environment:
      MYSQL_DATABASE: techmovil_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - techmovil-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    ports:
      - "9001:9000"
    networks:
      - techmovil-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    networks:
      - techmovil-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - techmovil-net

  k6:
    image: loadimpact/k6
    networks:
      - techmovil-net
    volumes:
      - .:/scripts

networks:
  techmovil-net:
    driver: bridge