name: techmovil

services:

  db:
    image: mysql:8.0
    container_name: techmovil_db
    restart: always
    environment:
      MYSQL_DATABASE: techmovil_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - techmovil-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    environment:
      SONAR_CE_JAVAOPTS: "-Xmx256m -Xms64m"
      SONAR_WEB_JAVAOPTS: "-Xmx256m -Xms64m"
      SONAR_SEARCH_JAVAOPTS: "-Xmx384m -Xms384m -XX:MaxDirectMemorySize=128m"
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - techmovil-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - techmovil-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb
    networks:
      - techmovil-net

  k6:
    image: loadimpact/k6
    networks:
      - techmovil-net
    volumes:
      - .:/scripts

networks:
  techmovil-net:
    driver: bridge

volumes:
  db_data:
  sonar_data:
  sonar_logs:
  sonar_extensions:
  jenkins_home:
  influx_data:
